frazes = [
"Down by the water",
"Tell the truth",
'Around the clock',
"Think before you act",
"Any old time",
"Read between the lines",
"Always be kind",
"In the big city",
"Leave it to me",
"First day of school",
"Ever since I knew you",
"It happened today",
"We need more space",
"What happened here?",
"Twenty four hours a day",
"Against all odds",
"Tried and true",
"Go figure",
"Today was better",
"Who brought the cake?",
"Twelve inches to a foot",
"I believe in you"
]